version: '3'

services:
  tiago-app-dev:
    build:
      context: ./
      target: runner
      args:
        - env=dev
    volumes:
      - .:/app
    command: yarn dev
    container_name: tiago-app-dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development